import React from 'react';
import type { CharacterVoice } from './utils/speech';



export type Line = [string, string];

export const talk = (who: string, lines: string[]): Line[] =>
  lines.map((t, i): Line => [i % 2 === 0 ? 'Orbit' : who, t]);

interface BeatInput {
  id: string;
  name: string; // chat speaker name (must match SPEAKERS in InterviewChat)
  voice?: CharacterVoice;
  lead: string; // short speech-bubble quote
  body: string; // one-paragraph kid summary
  speech: string; // spoken line for the illustration
  fact: string; // "NASA Discovery" box
  chat: string[];
  emoji: string;
  year: string;
  orbitLine: string;
}

const mk = (b: BeatInput) => ({
  id: b.id,
  pageNumber: 0,
  layout: 'both_generic' as const,
  speaker: (b.voice ?? 'narrator') as CharacterVoice,
  speakerName: `${b.name} & Orbit`,
  isConversation: true,
  orangeVariant: 'meridiani' as const,
  leadQuote: b.lead,
  bodyComponent: <span>{b.body}</span>,
  speechText: b.speech,
  scienceFact: b.fact,
  interview: talk(b.name, b.chat),
  art: { emoji: b.emoji, name: b.name, year: b.year },
  orbitLine: b.orbitLine,
});

/* ------------------------------------------------------------------ */
/*  REWRITTEN INTERVIEWS FOR THE EXISTING CHARACTERS (applied by id)   */
/* ------------------------------------------------------------------ */
export const REWRITTEN: Record<string, Line[]> = {
  'mars-viking-1': talk('Viking 1', [
    'Viking 1, you went to Mars in the 1970s. What was the big plan?',
    'Land safely, look around, and find out if anything on Mars might be alive!',
    'How do you look for life?',
    'I scooped up soil with my robot arm and tested it in a tiny biology lab inside me.',
    'So… did you find any?',
    'My tests gave puzzling answers. Nobody could say for sure. But I learned so much about Mars soil and weather!',
    'Weather? You had a weather station too?',
    'A weather mast, two cameras, and a {{seismometer|quake sensor}}. I was a busy robot!',
    'How long did you work?',
    'Until November 1982. That is six years! Then my signal faded.',
    'And you are still there?',
    'Still sitting on Mars right where I landed, quiet but proud.',
    'You did an amazing job, Viking 1.',
  ]),
  'mars-sojourner': talk('Sojourner', [
    'Sojourner, you are so small! What was your job on Mars?',
    'I rolled off my lander and checked out rocks, up close!',
    'How do you check a rock?',
    'I press a {{spectrometer|rock-chemistry sensor}} against it, and it tells me what the rock is made of.',
    'And how big are you, exactly?',
    'About the size of a microwave oven, with six wheels.',
    'How long were you supposed to last?',
    'Only 7 days! But I kept going for 83!',
    'Ha! What did your adventure teach us?',
    'That little rovers can explore Mars. After me, NASA sent bigger ones!',
    'Where are you now?',
    'Resting near my lander at {{ares_vallis|Ares Vallis}}. We called home for the last time in 1997.',
    'Thanks for paving the way, little rover.',
  ]),
  'mars-spirit': talk('Spirit', [
    'Spirit, what were you hunting for on Mars?',
    'Clues about water! Was Mars wet long ago?',
    'Where did you go to look?',
    'To {{gusev|Gusev Crater}}. Scientists thought it might once have been a lake.',
    'What tools did you have?',
    'Six wheels, cameras, and a robot arm that could scrape rock and read what is inside.',
    'And what did you find?',
    'Yes! Rocks that water had changed. Mars was once wet!',
    'You were only meant to work for 90 days, weren’t you?',
    'Yes, and I worked for over six years! I drove almost 8 kilometers.',
    'What happened to you?',
    'In 2009 I got stuck in soft sand, and my solar panels could not get enough light. My last call was in 2010.',
    'You’re still on Mars, with all you found.',
  ]),
  'mars-opportunity': talk('Oppy', [
    'Oppy, I hear you found blueberries on Mars!',
    'Not the kind you eat! Tiny round rocks called {{blueberries|blueberries}}. They grow in water.',
    'So water was there?',
    'Yes! I landed on a flat red plain called {{meridiani|Meridiani Planum}}, and the rocks told me water had soaked in.',
    'What helped you find all that?',
    'Cameras, a robot arm, and sensors for reading rocks. And big solar panels to power me.',
    'How long were you supposed to explore?',
    '90 days. I lasted more than 14 years!',
    'Wow. What stopped you?',
    'A giant dust storm covered my sunlight. I sent my last message in June 2018.',
    'Where did you end up?',
    'In {{perseverance_valley|Perseverance Valley}}, still looking out over Mars.',
    'You made us all proud, Oppy.',
  ]),
  'moon-surveyor-1': talk('Surveyor 1', [
    'Surveyor 1, you landed on the Moon before any people did. Why?',
    'Someone had to check that the ground would hold a spaceship up!',
    'What were you built like?',
    'Three legs, a TV camera, and a {{retrorocket|braking rocket}} to slow my fall. 🌕',
    'Did the landing go well?',
    'Softly! I was the first U.S. spacecraft to do it, in the {{ocean_storms|Ocean of Storms}}.',
    'What did you send home?',
    'More than 11,000 pictures, and tests of how firm the ground was.',
    'And what did scientists decide?',
    'That the Moon was safe to land on. That helped Apollo get ready!',
    'Are you still there?',
    'Yes. My pictures stopped in 1966, and my last contact was in January 1967.',
    'A true Moon pioneer.',
  ]),
  'moon-grail-a': talk('GRAIL-A (Ebb)', [
    'Ebb, you and Flow flew together. Why?',
    'To map the Moon’s gravity! Heavy ground under the surface tugs on us a little harder.',
    'How could you feel that?',
    'We flew one behind the other and used radio to measure how far apart we were. When that distance changed, we knew the ground below was different.',
    'That’s clever! What did you find?',
    'The Moon’s outer shell is thinner than people thought, and it is full of old cracks.',
    'What were you like?',
    'About as big as a washing machine!',
    'How did your mission end?',
    'In December 2012 we dived into a mountain near the north pole, on purpose.',
    'Why on purpose?',
    'We were out of fuel, and this way we knew exactly where we would end up.',
    'You went out together, Ebb. Thank you.',
  ]),
  'moon-grail-b': talk('GRAIL-B (Flow)', [
    'Flow! Ebb says you two flew in a line.',
    'We did! We were each other’s measuring tape.',
    'And you got your names from kids, right?',
    'Yes! Students in Montana picked Ebb and Flow, like the ocean tides.',
    'What did your team learn?',
    'We made the best gravity map of any world, and it showed us what is hidden inside the Moon.',
    'Was it hard work?',
    'Not with a friend. We tracked each other with radio, round and round the Moon.',
    'What happened at the end?',
    'We crashed together near the north pole in December 2012.',
    'Are you still up there?',
    'Yes. Both of us, side by side.',
    'The perfect pair.',
  ]),
  'moon-apollo-11': talk('Apollo 11', [
    'Apollo 11, you were the first to land people on the Moon!',
    'We were! We carried two astronauts down in a lander called Eagle.',
    'The bottom half of Eagle never came home, did it?',
    'It is still there. It worked like a launch pad for the top half, which flew the crew back to orbit.',
    'Where exactly is it?',
    'At {{tranquility_base|Tranquility Base}}, in the {{sea_tranquility|Sea of Tranquility}}.',
    'Did you leave anything useful?',
    'A {{seismometer|quake sensor}} to feel the Moon shake, and a mirror that scientists still shoot lasers at!',
    'What did the astronauts bring back?',
    'About 21 kilograms of Moon rocks. Scientists are still studying them.',
    'Does the lander still work?',
    'No, it went quiet in 1969, but the footprints are still there.',
    'First footprints, forever.',
  ]),
  'moon-apollo-15': talk('Apollo 15', [
    'Apollo 15, did you really drive a car on the Moon?',
    'Yes! We were the first crew with a Lunar Roving Vehicle.',
    'How did it fit in your lander?',
    'It folded up like a picnic chair! Unfolded, it was a four-wheeled, battery-powered rover.',
    'Where did you drive it?',
    'Around {{hadley|Hadley-Apennine}}, beside tall mountains and a deep winding canyon.',
    'What did the rover let you do?',
    'Go much farther from the lander, and carry back rocks. We drove nearly 28 kilometers!',
    'Where is the rover now?',
    'Parked near our landing site, right where we left it in 1971.',
    'Does it still run?',
    'No, but I like to think it is waiting.',
    'Moon parking at its best!',
  ]),
  'deep-pioneer-5': talk('Pioneer 5', [
    'Pioneer 5, you are one of the oldest explorers here!',
    'I flew in 1960, to study the Sun and the space between Earth and Venus.',
    'What was inside you?',
    'Sensors for magnetism and {{solar_particles|solar particles}}. I was a small, spinning ball with solar cells.',
    'What did you learn?',
    'That the Sun sends particles and magnetism all through space. Scientists used that to understand space weather.',
    'Did you keep talking to Earth for long?',
    'A few months. My last signal came in June 1960.',
    'Why did you stop?',
    'I got too far away and my signal grew too weak.',
    'So where are you now?',
    'Still circling the Sun, all by myself.',
    'Still going around, after all these years!',
  ]),
  'deep-mariner-2': talk('Mariner 2', [
    'Mariner 2, you were the first to visit another planet!',
    'Yes! I flew past Venus in December 1962.',
    'What did you find out?',
    'Venus is scorching hot, much hotter than anyone guessed!',
    'How did you tell?',
    'I carried {{radiometer|heat sensors}} that could feel Venus’s warmth from far away.',
    'Anything else?',
    'I measured the wind coming from the Sun, all the way there.',
    'How did you get your power?',
    'Two solar panels, and a dish antenna to talk to Earth.',
    'And where are you now?',
    'Circling the Sun. I went quiet in January 1963.',
    'First to Venus. Nice work!',
  ]),
  'deep-mariner-10': talk('Mariner 10', [
    'Mariner 10, how did you get to Mercury?',
    'I used a trick! I swung past Venus and let its gravity throw me toward Mercury.',
    'A {{gravity_assist|gravity boost}}?',
    'Yes! I was the first spacecraft to try it.',
    'What did you see at Mercury?',
    'A world covered in craters, like the Moon. And a magnetic field, which nobody expected!',
    'How did you see all that?',
    'Cameras and a {{magnetometer|magnet sensor}}. I flew by Mercury three times.',
    'Why did you stop talking?',
    'In March 1975 I ran out of gas for steering. I could not point my antenna at Earth anymore.',
    'Where are you now?',
    'Going around the Sun, quiet but happy.',
    'Your Mercury adventure lives on!',
  ]),
  'deep-pioneer-10': talk('Pioneer 10', [
    'Pioneer 10, you went all the way to Jupiter!',
    'I did! I was the first to cross the {{asteroid_belt|asteroid belt}} and visit the giant planet.',
    'Was it scary?',
    'A little! Jupiter has strong radiation. But I measured it, and that helped design later spacecraft.',
    'What were you made of?',
    'A big dish antenna, and a {{rtg|nuclear battery}} for power, since the Sun is so faint out there.',
    'Do you carry anything special?',
    'A golden plaque with a message, in case someone finds me.',
    'Are you still talking to Earth?',
    'No. My last signal came in January 2003. My power was too weak.',
    'So where are you?',
    'Still heading out into the dark, toward the stars.',
    'Quietly traveling, Pioneer 10.',
  ]),
  'deep-pioneer-11': talk('Pioneer 11', [
    'Pioneer 11, you visited two giant planets!',
    'Jupiter first, then Saturn! I was the first spacecraft to fly past Saturn.',
    'What did you see?',
    'Close-ups of Saturn and its rings. And I spotted a new ring nobody knew about!',
    'How did you do it?',
    'Cameras, a {{magnetometer|magnet sensor}}, and a {{rtg|nuclear battery}} for power.',
    'Did you follow Pioneer 10?',
    'Sort of! It showed me what Jupiter was like, so I could go in safer.',
    'Are you still in touch?',
    'My last contact with Earth was in 1995.',
    'Where are you now?',
    'Still moving away from the Sun.',
    'Another pioneer heading into the dark.',
  ]),
  'deep-voyager-1': talk('Voyager 1', [
    'Voyager 1, you were only meant to visit Jupiter and Saturn, right?',
    'Yes. And then I just… kept going.',
    'What did you see at those planets?',
    'Giant storms, volcanoes on a moon called Io, and Saturn’s rings up close.',
    'And then you went even farther?',
    'In 2012 I crossed into {{interstellar|interstellar space}}. That is the space between the stars.',
    'What keeps you going?',
    'A {{rtg|nuclear battery}}, a big dish antenna, and a Golden Record with sounds and pictures from Earth.',
    'Do you still talk to Earth?',
    'Yes! I send a little science and engineering data, even though I am old.',
    'You are the farthest explorer ever.',
    'And I will keep going.',
    'The little traveler that just won’t stop!',
  ]),
};

/* ------------------------------------------------------------------ */
/*  MARS                                                               */
/* ------------------------------------------------------------------ */
export const MARS_EXTRA = [
  mk({
    id: 'mars-viking-2', name: 'Viking 2', voice: 'viking1', emoji: '🔭', year: '1976',
    lead: 'I looked at frost on Mars!',
    body: 'Viking 2 landed on the northern plains of Mars in 1976 to study the soil, air and weather. It worked until April 1980.',
    speech: 'I landed on the northern plains of Mars in 1976 and kept working until 1980!',
    fact: 'Viking 2 worked until 11 April 1980, when its batteries failed.',
    orbitLine: 'Viking 2, what did you see on Mars?',
    chat: [
      'Viking 2, you landed on Mars just after your twin. Where did you go?',
      'Way up north, on a cold, flat plain called {{utopia|Utopia Planitia}}.',
      'Was it cold?',
      'Freezing! I even saw a thin coat of frost on the ground when the cold season came.',
      'Frost on Mars! How did you notice?',
      'My cameras took pictures every day. I also had a weather mast, a soil-scooping arm, and a {{seismometer|quake sensor}}.',
      'What were you hoping to learn?',
      'Mostly the same as Viking 1: what the soil is made of, and whether anything lives in it.',
      'And did you find life?',
      'My tests were puzzling, but I learned so much about Mars soil and weather.',
      'Why did you stop working?',
      'My batteries gave out in April 1980.',
      'Are you still there?',
      'Yes, right where I landed. Quiet and cold.',
      'Thanks, Viking 2.',
    ],
  }),
  mk({
    id: 'mars-viking-1-orbiter', name: 'Viking 1 Orbiter', voice: 'viking1', emoji: '🛰️', year: '1975',
    lead: 'I took the pictures from above!',
    body: 'The Viking 1 Orbiter circled Mars, photographed the planet, and passed messages for its lander. It worked until August 1980.',
    speech: 'I circled Mars, mapped it from above, and passed messages for my lander!',
    fact: 'The Viking orbiters photographed most of Mars from space, helping pick landing sites.',
    orbitLine: 'Viking 1 Orbiter, what did you do up there?',
    chat: [
      'Viking 1 Orbiter, you stayed up in the sky while your lander went down. What was your job?',
      'I was the eyes in the sky! I photographed Mars and helped find a safe place to land.',
      'And after landing?',
      'I passed messages between my lander and Earth. A bit like a postman!',
      'What did you see from up there?',
      'Giant volcanoes, enormous canyons, and old channels that look like water carved them.',
      'Water, again!',
      'Yes! That made scientists even more curious.',
      'What tools did you have?',
      'Cameras, plus sensors for heat and water vapor in the air.',
      'Why did you stop working?',
      'I ran low on the gas I used for steering. We lost touch in August 1980.',
      'Where are you now?',
      'Still circling Mars, quietly.',
      'A great helper to your lander.',
    ],
  }),
  mk({
    id: 'mars-viking-2-orbiter', name: 'Viking 2 Orbiter', voice: 'viking1', emoji: '🛰️', year: '1975',
    lead: 'A gas leak ended my mission.',
    body: 'The Viking 2 Orbiter mapped Mars from above for about two years before a gas leak ended its mission in 1978.',
    speech: 'I mapped Mars from above until a gas leak ended my mission in 1978.',
    fact: 'The Viking 2 Orbiter was shut down in July 1978 after a leak drained its steering gas.',
    orbitLine: 'Viking 2 Orbiter, what happened to you?',
    chat: [
      'Viking 2 Orbiter, you flew over Mars for a couple of years. What did you do?',
      'I took thousands of pictures of the surface and kept an eye on the weather.',
      'What did the pictures show?',
      'Channels, canyons, and volcanoes. Even Mars’s two tiny moons!',
      'You looked at moons too?',
      'I flew close to one of them. It looks like a lumpy potato!',
      'What were you built with?',
      'Two cameras, and sensors for heat and water vapor. And a dish to talk to my lander.',
      'What went wrong?',
      'A leak drained my steering gas, so I could not point properly.',
      'When did that happen?',
      'In 1978. I was shut off in July.',
      'Are you still there?',
      'Still circling Mars, quietly.',
      'Thanks for the pictures, Viking 2 Orbiter.',
    ],
  }),
  mk({
    id: 'mars-mariner-4', name: 'Mariner 4', voice: 'mariner2', emoji: '📸', year: '1964',
    lead: 'I took the first close-ups of Mars!',
    body: 'Mariner 4 flew past Mars in July 1965 and took the first close-up pictures of another planet.',
    speech: 'I flew past Mars in 1965 and took the first close-up pictures of the planet!',
    fact: 'Mariner 4 showed Mars is covered in craters and has very thin air. Its last contact was 21 December 1967.',
    orbitLine: 'Mariner 4, what did Mars look like?',
    chat: [
      'Mariner 4, you were the first to take close-up pictures of Mars!',
      'I was! I zoomed past in July 1965, in a quick flyby.',
      'What were people expecting?',
      'Some hoped for rivers and green plants. Others thought maybe canals!',
      'And what did you actually see?',
      'Craters! Mars looked more like the Moon than like Earth.',
      'How did you take pictures?',
      'I had one TV camera. I took about 21 pictures, and sent them home bit by bit.',
      'Was Mars’s {{atmosphere|air}} what people expected?',
      'It is very thin, much thinner than anyone thought.',
      'How long did you keep talking to Earth?',
      'Until December 1967.',
      'And now?',
      'I am orbiting the Sun, and quiet.',
      'Thank you for the first look, Mariner 4.',
    ],
  }),
  mk({
    id: 'mars-mariner-6', name: 'Mariner 6', voice: 'mariner2', emoji: '📸', year: '1969',
    lead: 'Two flybys, double the pictures!',
    body: 'Mariner 6 flew past Mars in 1969 with its twin, Mariner 7, to photograph it and study its air.',
    speech: 'My twin and I flew past Mars in 1969 and studied its air and surface!',
    fact: 'Mariners 6 and 7 found that Mars’s air is mostly carbon dioxide and sent about 200 pictures.',
    orbitLine: 'Mariner 6, tell us about your Mars flyby!',
    chat: [
      'Mariner 6, you went to Mars with a twin!',
      'Yes, Mariner 7 flew with me. We flew past a few days apart in 1969.',
      'Why two spacecraft?',
      'Two chances to get it right! And we could look at different parts of Mars.',
      'What did you take with you?',
      'Two TV cameras, and sensors for light and heat.',
      'And what did you learn?',
      'That Mars’s air is mostly carbon dioxide. And we saw craters and bright polar caps.',
      'Did you chat with Earth for long?',
      'NASA’s records don’t say exactly when I stopped. It was a long time ago!',
      'Where are you now?',
      'Going around the Sun.',
      'Teamwork makes the flyby work!',
    ],
  }),
  mk({
    id: 'mars-mariner-7', name: 'Mariner 7', voice: 'mariner2', emoji: '📸', year: '1969',
    lead: 'I came in over the south pole!',
    body: 'Mariner 7 flew past Mars days after Mariner 6 and sent back even more pictures.',
    speech: 'I flew past Mars days after my twin and sent back even more pictures!',
    fact: 'Mariner 7 flew over Mars’s south pole. Its data showed the polar cap is mostly frozen carbon dioxide.',
    orbitLine: 'Mariner 7, what did you see?',
    chat: [
      'Mariner 7, you followed Mariner 6 to Mars. What did you focus on?',
      'The south pole! I flew over it to see its icy cap.',
      'What is it made of?',
      'Mostly dry ice, which is frozen carbon dioxide. Not water ice!',
      'That’s surprising!',
      'It surprised the scientists too!',
      'Did you take lots of pictures?',
      'Even more than my twin, about 126!',
      'What were you carrying?',
      'The same as Mariner 6: TV cameras and sensors for light and heat.',
      'Are you still talking to Earth?',
      'No. NASA’s records don’t say when I went quiet.',
      'And where are you now?',
      'Orbiting the Sun.',
      'Great teamwork, you two!',
    ],
  }),
  mk({
    id: 'mars-observer', name: 'Mars Observer', voice: 'narrator', emoji: '📡', year: '1992',
    lead: 'I vanished three days early.',
    body: 'Mars Observer was the first U.S. mission to Mars in 18 years. Contact was lost on 21 August 1993, three days before it arrived.',
    speech: 'I was three days from Mars when contact was lost in 1993.',
    fact: 'Investigators think a fuel leak damaged Mars Observer’s fuel pipes.',
    orbitLine: 'Mars Observer, what went wrong?',
    chat: [
      'Mars Observer, you were so close to Mars. What happened?',
      'I was only three days away. Then, silence.',
      'What was your plan?',
      'To circle Mars and study its ground, its air, and its magnetism for a whole Mars year.',
      'What did you carry?',
      'A camera, a {{altimeter|laser height-meter}}, and sensors for rock chemistry and heat.',
      'Why did you go quiet?',
      'Investigators think a fuel leak damaged my pipes when my tanks were being filled with gas.',
      'So you never reached Mars?',
      'No. I never sent any science back.',
      'That’s sad.',
      'But my instruments were rebuilt and flew on later missions, so some of me made it!',
      'And where are you now?',
      'No one knows. Nobody has heard from me since 1993.',
      'We’re glad part of you got to Mars.',
    ],
  }),
  mk({
    id: 'mars-global-surveyor', name: 'Mars Global Surveyor', voice: 'narrator', emoji: '🛰️', year: '1996',
    lead: 'I mapped Mars for nine years!',
    body: 'Mars Global Surveyor circled Mars from 1997 until it went quiet on 2 November 2006.',
    speech: 'I mapped Mars from orbit for nine years, until I went silent in 2006.',
    fact: 'Mars Global Surveyor found gullies, layered rocks, and magnetic stripes in the crust of Mars.',
    orbitLine: 'Mars Global Surveyor, what did you map?',
    chat: [
      'Mars Global Surveyor, you stayed around Mars for years. What was your job?',
      'To make a map of the whole planet, from above!',
      'How did you map it?',
      'With a sharp camera, and a {{altimeter|laser height-meter}} that measured how high the land is.',
      'What did you find?',
      'Layers of rock, like pages in a book. And gullies that might have been cut by flowing liquid!',
      'Anything else?',
      'Stripes of old magnetism hidden in the ground. They hint at how Mars changed long ago.',
      'You had a {{magnetometer|magnet sensor}}, right?',
      'Yes, that is how I found them!',
      'How long did you last?',
      'Nine years! Until November 2006.',
      'Where are you now?',
      'Still circling Mars.',
      'Thanks for the map, Mars Global Surveyor.',
    ],
  }),
  mk({
    id: 'mars-climate-orbiter', name: 'Mars Climate Orbiter', voice: 'narrator', emoji: '📏', year: '1998',
    lead: 'A units mix-up sent me too low.',
    body: 'Mars Climate Orbiter reached Mars on 23 September 1999 but flew far too low. Some engineers had used English units while others used metric.',
    speech: 'A units mix-up sent me too close to Mars in 1999.',
    fact: 'Mars Climate Orbiter passed at about 57 km above Mars instead of the planned 140–150 km, because of a pounds versus newtons mix-up.',
    orbitLine: 'Mars Climate Orbiter, what went wrong?',
    chat: [
      'Mars Climate Orbiter, I heard your trip ended in a mix-up.',
      'Yes. One team used English units, like pounds. Another used metric, like newtons.',
      'And the computer didn’t know?',
      'No! So my path was off. I flew way lower than planned.',
      'How low?',
      'About 57 kilometers above Mars, when I should have been much higher.',
      'What happened then?',
      'Mars’s thick air probably damaged me. We lost contact on 23 September 1999.',
      'What was your mission supposed to be?',
      'To study Mars’s weather and climate, and to relay messages for landers.',
      'What were you carrying?',
      'A weather camera, a {{radiometer|heat sensor}}, and big solar panels.',
      'Where are you now?',
      'I either burned up or flew past Mars. We don’t know.',
      'A tiny mix-up, but a huge lesson. Thank you.',
    ],
  }),
  mk({
    id: 'mars-polar-lander', name: 'Mars Polar Lander', voice: 'narrator', emoji: '🪂', year: '1999',
    lead: 'I never called home.',
    body: 'Mars Polar Lander was meant to land near Mars’s south pole in December 1999. It never called Earth after landing.',
    speech: 'I was supposed to land near Mars’s south pole, but I never called home.',
    fact: 'The last signal from Mars Polar Lander came just before it entered Mars’s air on 3 December 1999. No one knows what went wrong.',
    orbitLine: 'Mars Polar Lander, what happened at the pole?',
    chat: [
      'Mars Polar Lander, you were headed for the south pole of Mars!',
      'Yes! I wanted to study the weather, the ice, and the soil there.',
      'What did you have with you?',
      'A robot arm, a camera, a laser for studying the sky, and even a microphone!',
      'A microphone? To hear Mars?',
      'Yes! It would have been the first time we heard the sounds of Mars.',
      'Did you bring any friends?',
      'Two tiny probes called Deep Space 2, built to dig into the ground.',
      'What happened when you landed?',
      'My last message came just before I entered Mars’s air, on 3 December 1999. Then nothing.',
      'Do we know why?',
      'No. Nobody knows for sure.',
      'Where are you now?',
      'Somewhere near the south pole, quiet.',
      'We’re still glad you tried, Mars Polar Lander.',
    ],
  }),
  mk({
    id: 'mars-phoenix', name: 'Phoenix', voice: 'sojourner', emoji: '❄️', year: '2007',
    lead: 'I dug up ice!',
    body: 'Phoenix landed on the cold northern plains of Mars in 2008, dug into the ground, and found water ice. The Sun faded and it went quiet in November 2008.',
    speech: 'I landed in the Martian arctic, dug into the ground, and found water ice!',
    fact: 'Phoenix sent its last message on 2 November 2008 as northern summer ended and sunlight faded.',
    orbitLine: 'Phoenix, what did you dig up?',
    chat: [
      'Phoenix, you landed way up north on Mars. Why there?',
      'Because scientists thought there might be ice hiding just under the soil!',
      'How did you check?',
      'With a robot arm and a scoop. I dug a trench and looked down.',
      'And what was there?',
      'White chunks that melted away over a few days. It was water ice!',
      'Was that a big deal?',
      'Yes! Water is a clue to whether Mars could ever have supported life.',
      'What else did you have onboard?',
      'A camera, a weather station, and a tiny chemistry lab for testing soil.',
      'How long did you work?',
      'Through the Martian summer. Then the Sun sank and my solar power ran out.',
      'When was that?',
      'My last message came on 2 November 2008.',
      'Are you still there?',
      'Frozen in the Martian north, with my ice.',
      'Thank you, Phoenix.',
    ],
  }),
  mk({
    id: 'mars-insight', name: 'InSight', voice: 'spirit', emoji: '🌍', year: '2018',
    lead: 'I listened for marsquakes!',
    body: 'InSight listened for marsquakes and measured heat from inside Mars. Dust covered its solar panels, and it stopped in December 2022.',
    speech: 'I listened for marsquakes and measured heat from inside Mars!',
    fact: 'InSight stopped talking after 5 December 2022. NASA declared the mission over on 21 December 2022.',
    orbitLine: 'InSight, what did you hear?',
    chat: [
      'InSight, you didn’t go exploring. You just sat still. Why?',
      'Because I was listening! I wanted to hear the inside of Mars.',
      'How can you hear that?',
      'With a very sensitive {{seismometer|quake sensor}}. It feels marsquakes, even tiny ones.',
      'Did you hear many?',
      'Hundreds! They showed scientists how Mars is built inside.',
      'What else did you carry?',
      'A heat probe that hammered itself into the ground, weather sensors, and two cameras.',
      'Where did you land?',
      'On a flat plain called {{elysium|Elysium Planitia}}.',
      'Why did you stop?',
      'Dust slowly covered my solar panels, so I had less power each day.',
      'When did we hear from you last?',
      'On 5 December 2022. Then I went quiet.',
      'You listened to a whole planet. Thank you.',
    ],
  }),
  mk({
    id: 'mars-ingenuity', name: 'Ingenuity', voice: 'oppy', emoji: '🚁', year: '2020',
    lead: 'I flew on another planet!',
    body: 'Ingenuity was a helicopter that proved flight is possible in the thin air of Mars. It made 72 flights before a rotor was damaged in January 2024.',
    speech: 'I was the first helicopter on another planet, and I flew 72 times!',
    fact: 'Ingenuity flew 72 times over almost three years before a damaged rotor blade ended its flights on 18 January 2024.',
    orbitLine: 'Ingenuity, tell us about flying on Mars!',
    chat: [
      'Ingenuity, you are a helicopter on Mars! How did you get there?',
      'I rode on the belly of the Perseverance rover!',
      'Was flying on Mars hard?',
      'Very! Mars’s {{atmosphere|air}} is so thin that I had to spin my blades super fast.',
      'How big are you?',
      'Tiny! I weigh about as much as a bag of sugar, and my blades are 1.2 meters wide.',
      'How many flights did NASA expect?',
      'Five. Just five!',
      'And how many did you do?',
      'Seventy-two!',
      'Wow! What did you do besides test flights?',
      'I scouted the ground ahead so Perseverance could pick safe paths.',
      'What ended your flying?',
      'In January 2024, one of my blades broke, so I could not fly again.',
      'Where are you now?',
      'Parked on Mars, near {{jezero|Jezero Crater}}.',
      'You proved we can fly on other worlds. Thank you!',
    ],
  }),
];

/* ------------------------------------------------------------------ */
/*  MOON                                                               */
/* ------------------------------------------------------------------ */
export const MOON_EXTRA = [
  mk({
    id: 'moon-ranger-7', name: 'Ranger 7', emoji: '📷', year: '1964',
    lead: 'My last picture was my best!',
    body: 'Ranger 7 was built to crash into the Moon while photographing it. Its cameras sent thousands of pictures on the way down.',
    speech: 'I took thousands of pictures on my way down to the Moon!',
    fact: 'Ranger 7 sent 4,308 pictures in its last 17 minutes before hitting the Moon on 31 July 1964.',
    orbitLine: 'Ranger 7, what did you see on the way down?',
    chat: [
      'Ranger 7, your mission was to crash into the Moon?',
      'On purpose! I took pictures the whole way down, and the closer I got, the sharper they were.',
      'Why would anyone want that?',
      'We needed close-up looks at the Moon before sending people. I was the first U.S. spacecraft to send those.',
      'What did you have onboard?',
      'Six TV cameras, and solar panels for power.',
      'How many pictures?',
      'More than four thousand, in the last 17 minutes!',
      'What did they show?',
      'That some Moon ground is smooth enough for a landing.',
      'Where did you end up?',
      'On a dark plain called {{mare_cognitum|Mare Cognitum}}. Still there, in pieces.',
      'You gave us our first close look. Thank you.',
    ],
  }),
  mk({
    id: 'moon-ranger-8', name: 'Ranger 8', emoji: '📷', year: '1965',
    lead: 'I scouted Apollo’s future landing area!',
    body: 'Ranger 8 photographed the Sea of Tranquility before crashing there on purpose in 1965.',
    speech: 'I photographed the Sea of Tranquility before I crashed on purpose in 1965!',
    fact: 'Ranger 8 sent 7,137 pictures in its last 23 minutes and hit the Moon on 20 February 1965.',
    orbitLine: 'Ranger 8, what did you see?',
    chat: [
      'Ranger 8, you followed Ranger 7. What was your plan?',
      'The same: dive toward the Moon, taking pictures all the way.',
      'Where did you dive?',
      'Into the {{sea_tranquility|Sea of Tranquility}}, a big smooth plain.',
      'Why was that important?',
      'Four years later, Apollo 11 landed near there!',
      'Wow! So you scouted it for them?',
      'My pictures helped show the ground was smooth enough.',
      'How many did you send?',
      'More than seven thousand!',
      'What were you built with?',
      'Six TV cameras, and a radio to send pictures back right away.',
      'And you’re still there?',
      'In pieces, in the Sea of Tranquility.',
      'A good scout, Ranger 8.',
    ],
  }),
  mk({
    id: 'moon-ranger-9', name: 'Ranger 9', emoji: '📺', year: '1965',
    lead: 'You watched me crash on TV!',
    body: 'Ranger 9 sent live pictures of a big Moon crater, shown on television, until it crashed in 1965.',
    speech: 'I sent live pictures of a big Moon crater until I crashed in 1965!',
    fact: 'Ranger 9 sent 5,814 pictures and hit the Moon on 24 March 1965. Many were shown live on TV.',
    orbitLine: 'Ranger 9, you were on TV!',
    chat: [
      'Ranger 9, people watched you on TV, live!',
      'Yes! My cameras sent pictures all the way down, and TV stations showed them as they came in.',
      'What were you aiming at?',
      'A big crater called {{alphonsus|Alphonsus}}, with a mountain peak in the middle.',
      'Why that crater?',
      'Scientists thought it might show signs of volcanic activity.',
      'How many cameras did you have?',
      'Six! And a radio to send everything right away.',
      'What did people see?',
      'The crater getting bigger and bigger, till I crashed.',
      'Where are you now?',
      'Inside Alphonsus, where I crashed on 24 March 1965.',
      'The last of the Rangers. Great show!',
    ],
  }),
  mk({
    id: 'moon-lunar-orbiter-1', name: 'Lunar Orbiter 1', emoji: '🛰️', year: '1966',
    lead: 'I scouted landing sites from orbit!',
    body: 'Lunar Orbiter 1 circled the Moon in 1966, photographing possible Apollo landing sites.',
    speech: 'I circled the Moon in 1966 and photographed possible Apollo landing sites!',
    fact: 'Lunar Orbiter 1 took the first picture of Earth from Moon orbit. It was crashed on purpose on 29 October 1966.',
    orbitLine: 'Lunar Orbiter 1, what did you scout?',
    chat: [
      'Lunar Orbiter 1, you circled the Moon instead of crashing into it!',
      'Yes! That way I could look at it for weeks.',
      'What were you looking for?',
      'Safe places for Apollo to land.',
      'How did you take pictures?',
      'With a camera that developed its own film, right inside me!',
      'Whoa! Then what?',
      'I scanned each picture and sent it to Earth by radio.',
      'What was your most famous picture?',
      'The first one of Earth from Moon orbit! A little blue ball over the gray ground.',
      'Why did your mission end early?',
      'My steering gas was low, and I had to stay out of Lunar Orbiter 2’s way.',
      'Where are you now?',
      'On the far side of the Moon. I was crashed there on purpose in October 1966.',
      'What a view you gave us!',
    ],
  }),
  mk({
    id: 'moon-lunar-orbiter-2', name: 'Lunar Orbiter 2', emoji: '🛰️', year: '1966',
    lead: 'I mapped the Moon’s craters.',
    body: 'Lunar Orbiter 2 took detailed photos of craters and landscape for the Apollo program.',
    speech: 'I mapped craters and landscape for Apollo!',
    fact: 'Lunar Orbiter 2 was crashed on purpose on 11 October 1967 after finishing its mission.',
    orbitLine: 'Lunar Orbiter 2, what did you map?',
    chat: [
      'Lunar Orbiter 2, I hear you took a famous picture.',
      'A slanted view across the giant crater {{copernicus|Copernicus}}! Like looking at it from an airplane.',
      'Why was it special?',
      'Most photos looked straight down. Mine showed the mountains in the middle and the tall walls.',
      'What was your main job?',
      'Mapping craters and hills, to help Apollo pick safe landing spots.',
      'How did you take the pictures?',
      'A film camera inside me. I developed and scanned the film, and sent it by radio.',
      'Did you check anything else?',
      'Radiation, and tiny space-dust hits. Because astronauts needed to be safe.',
      'How did your mission end?',
      'I was crashed on purpose in October 1967.',
      'Where are you now?',
      'On the Moon, in my own little crater.',
      'Great work, Lunar Orbiter 2.',
    ],
  }),
  mk({
    id: 'moon-lunar-orbiter-3', name: 'Lunar Orbiter 3', emoji: '🛰️', year: '1967',
    lead: 'I found Surveyor 1!',
    body: 'Lunar Orbiter 3 helped confirm safe landing sites, and even spotted the Surveyor 1 lander.',
    speech: 'I helped confirm safe landing sites, and I spotted Surveyor 1!',
    fact: 'Lunar Orbiter 3 was crashed on purpose on 9 October 1967.',
    orbitLine: 'Lunar Orbiter 3, what did you spot?',
    chat: [
      'Lunar Orbiter 3, I hear you spotted another spacecraft!',
      'I did! Surveyor 1, sitting on the ground, all by itself.',
      'How could you see it?',
      'My camera was sharp enough to pick out its shadow.',
      'What was your main job?',
      'Checking landing sites for Surveyor and Apollo, to make sure they were safe.',
      'What did you carry besides the camera?',
      'Sensors for radiation, and tiny space-dust hits.',
      'Did you find good sites?',
      'Yes! Smooth places with few big rocks.',
      'How did your mission end?',
      'I was crashed on purpose in October 1967.',
      'Where are you now?',
      'On the Moon, at my crash site.',
      'Thanks, Lunar Orbiter 3!',
    ],
  }),
  mk({
    id: 'moon-lunar-orbiter-4', name: 'Lunar Orbiter 4', emoji: '🛰️', year: '1967',
    lead: 'I mapped the near side!',
    body: 'Lunar Orbiter 4 photographed about 99% of the Moon’s near side. Contact was lost on 17 July 1967.',
    speech: 'I mapped almost the whole near side of the Moon!',
    fact: 'Lunar Orbiter 4 lost contact on 17 July 1967. Its orbit shrank, and it probably hit the Moon by 31 October 1967.',
    orbitLine: 'Lunar Orbiter 4, what did you map?',
    chat: [
      'Lunar Orbiter 4, you took on a huge job. What was it?',
      'Mapping the whole side of the Moon that faces Earth!',
      'And did you do it?',
      'Almost all of it, about 99 percent!',
      'Why map the whole thing?',
      'So scientists could study every part, and Apollo could pick the best places.',
      'What did you carry?',
      'A film camera, and sensors for radiation and tiny space-dust hits.',
      'What happened at the end?',
      'I lost contact on 17 July 1967.',
      'Why?',
      'Nobody knows for sure. My orbit slowly shrank.',
      'So where are you?',
      'Probably on the Moon. I likely crashed by October 1967.',
      'A mapmaker to the end, Lunar Orbiter 4.',
    ],
  }),
  mk({
    id: 'moon-lunar-orbiter-5', name: 'Lunar Orbiter 5', emoji: '🛰️', year: '1967',
    lead: 'The last Orbiter finished the job!',
    body: 'Lunar Orbiter 5 photographed more landing sites and unmapped areas before it was crashed on 31 January 1968.',
    speech: 'I finished the mapping job, and photographed regions nobody had seen!',
    fact: 'Lunar Orbiter 5 ended on 31 January 1968 when it was crashed on purpose.',
    orbitLine: 'Lunar Orbiter 5, the last in the series!',
    chat: [
      'Lunar Orbiter 5, you were the last of the five Orbiters!',
      'Yes! I had the job of finishing the map.',
      'What was left to do?',
      'Places nobody had photographed yet, plus a second look at Apollo and Surveyor sites.',
      'How did you do it?',
      'Same as my brothers: a film camera, and sensors for radiation and space dust.',
      'How was it, finishing the whole series?',
      'It felt great! Between us, we mapped the whole Moon.',
      'How did you end?',
      'I was crashed on purpose in January 1968.',
      'Where are you?',
      'On the Moon, at my crash site.',
      'The whole Moon, mapped. Thank you!',
    ],
  }),
  mk({
    id: 'moon-surveyor-2', name: 'Surveyor 2', emoji: '💥', year: '1966',
    lead: 'One engine did not start.',
    body: 'Surveyor 2 was meant to land softly, but one of its engines failed on the way and it tumbled and crashed.',
    speech: 'One of my engines failed to start, and I crashed in 1966.',
    fact: 'A small steering engine failed on 21 September 1966, making Surveyor 2 spin. It crashed on the Moon on 22 September 1966.',
    orbitLine: 'Surveyor 2, what went wrong?',
    chat: [
      'Surveyor 2, you didn’t land the way you hoped.',
      'No. I was supposed to touch down softly and take pictures.',
      'What happened?',
      'One of my small steering engines didn’t start.',
      'What did that do?',
      'I began to spin, about once every second. Engineers tried everything, but couldn’t fix it.',
      'What were you built with?',
      'Three legs, a TV camera, and steering engines. Just like Surveyor 1.',
      'When did you crash?',
      'On 22 September 1966.',
      'Did you send any science?',
      'No. But my failure taught engineers how to fix later Surveyors.',
      'Where are you now?',
      'On the Moon, in a crater I made.',
      'Every mission teaches us something.',
    ],
  }),
  mk({
    id: 'moon-surveyor-3', name: 'Surveyor 3', emoji: '🤖', year: '1967',
    lead: 'Apollo 12 came to visit me!',
    body: 'Surveyor 3 landed in 1967. Two years later, Apollo 12 astronauts landed nearby and brought back some of its parts.',
    speech: 'Apollo 12 astronauts landed near me and took my camera home!',
    fact: 'Apollo 12 landed within 180 m of Surveyor 3 and brought back about 10 kg of its parts, including its TV camera.',
    orbitLine: 'Surveyor 3, what was it like to have visitors?',
    chat: [
      'Surveyor 3, I heard you got visitors on the Moon!',
      'I did! Two Apollo 12 astronauts walked right up to me in 1969.',
      'Before that, what were you doing?',
      'Checking if the ground was safe for people. I had a TV camera, and a little scoop arm to dig trenches.',
      'What did you find?',
      'The soil was firm enough to walk on!',
      'What did the astronauts do?',
      'They took pieces of me home, including my camera.',
      'Why?',
      'Scientists wanted to see how two years on the Moon changed them.',
      'Where is your camera now?',
      'In a museum!',
      'And you?',
      'Still on the Moon. My last call was in May 1967.',
      'Pretty cool to have visitors!',
    ],
  }),
  mk({
    id: 'moon-surveyor-4', name: 'Surveyor 4', emoji: '❓', year: '1967',
    lead: 'I lost contact just before landing.',
    body: 'Surveyor 4 went silent about two and a half minutes before landing in July 1967.',
    speech: 'I lost contact just before touchdown on the Moon in 1967.',
    fact: 'Surveyor 4’s signal stopped 41 seconds after its braking rocket fired on 17 July 1967. No one knows why.',
    orbitLine: 'Surveyor 4, what happened?',
    chat: [
      'Surveyor 4, you were so close to landing.',
      'Only about two and a half minutes away!',
      'What happened?',
      'My {{retrorocket|braking rocket}} fired, and 41 seconds later my signal stopped.',
      'Do we know why?',
      'No. Maybe the rocket failed, or maybe my radio did.',
      'What were you carrying?',
      'Three legs, a TV camera, and a soil scoop. I was going to test the ground.',
      'So you didn’t send science?',
      'No. But engineers studied what went wrong, to help later missions.',
      'Where are you now?',
      'Probably on the Moon. We never heard from me again.',
      'You tried your best, Surveyor 4.',
    ],
  }),
  mk({
    id: 'moon-surveyor-5', name: 'Surveyor 5', emoji: '🧪', year: '1967',
    lead: 'I tested the Moon’s chemistry!',
    body: 'Surveyor 5 made the first on-the-spot chemistry test of another world’s ground.',
    speech: 'I made the first chemistry test of another world’s soil!',
    fact: 'Surveyor 5 sent back 19,118 pictures. Its last message came on 17 December 1967.',
    orbitLine: 'Surveyor 5, what is the Moon made of?',
    chat: [
      'Surveyor 5, you did something new: you tested Moon soil!',
      'Right where I stood. I was the first to do it on another world.',
      'How?',
      'I had a {{spectrometer|rock-chemistry sensor}} on a little cord that I lowered to the ground.',
      'What did it find?',
      'The soil is like {{basalt|basalt}}, a dark rock that forms when lava cools.',
      'Where did you land?',
      'In the {{sea_tranquility|Sea of Tranquility}}, where Apollo 11 landed later.',
      'What else did you do?',
      'Took more than 19,000 pictures, over four Moon days!',
      'And now?',
      'Still on the Moon. I made my last call on 17 December 1967.',
      'A chemist on the Moon!',
    ],
  }),
  mk({
    id: 'moon-surveyor-6', name: 'Surveyor 6', emoji: '🦘', year: '1967',
    lead: 'I hopped on the Moon!',
    body: 'Surveyor 6 made the first takeoff from the Moon: a hop of a few meters.',
    speech: 'I hopped on the Moon!',
    fact: 'On 17 November 1967, Surveyor 6 lifted off and landed about 2.4 m away, giving two views of the same spot.',
    orbitLine: 'Surveyor 6, you hopped?!',
    chat: [
      'Surveyor 6, is it true you hopped on the Moon?',
      'Yes! I fired my engines for a moment and jumped a few meters.',
      'Why?',
      'To see if I could, and to take pictures from two spots.',
      'What did the two views give you?',
      '3D pictures of the ground!',
      'Where were you?',
      'In a place called {{sinus_medii|Sinus Medii}}, near the middle of the Moon’s face.',
      'What did you find?',
      'The soil is {{basalt|basalt}}-like, and strong enough for people to land on. That made Apollo feel safer.',
      'How many pictures?',
      'Nearly 30,000!',
      'And now?',
      'Still in my second spot. My last message was in December 1967.',
      'The first hop on the Moon!',
    ],
  }),
  mk({
    id: 'moon-surveyor-7', name: 'Surveyor 7', emoji: '⛰️', year: '1968',
    lead: 'I visited the Moon’s highlands!',
    body: 'Surveyor 7 landed in the rugged highlands near Tycho crater and detected laser beams sent from Earth.',
    speech: 'I explored the highlands near Tycho crater!',
    fact: 'Surveyor 7 sent 21,038 pictures. Highland soil had less iron than the dark plains.',
    orbitLine: 'Surveyor 7, what did you find at Tycho?',
    chat: [
      'Surveyor 7, you landed in a rugged place!',
      'Near the big crater {{tycho|Tycho}}, in the Moon’s highlands. All the others landed on flat plains.',
      'What did you want to know?',
      'Whether the highlands are different from the flat plains.',
      'How did you check?',
      'A scoop arm that dug trenches and moved rocks, and a {{spectrometer|rock-chemistry sensor}}.',
      'And what did you find?',
      'Highland soil has less iron. They really are different!',
      'Did anything cool happen?',
      'Yes! I saw laser beams sent from Earth!',
      'How did your mission end?',
      'After two Moon days, in February 1968.',
      'The last Surveyor. Great job!',
    ],
  }),
  mk({
    id: 'moon-apollo-12', name: 'Apollo 12', voice: 'apollo', emoji: '🚀', year: '1969',
    lead: 'We landed right next to Surveyor 3!',
    body: 'Apollo 12 landed within about 180 meters of Surveyor 3, left a science station, and brought home 34 kg of samples.',
    speech: 'We landed right next to Surveyor 3!',
    fact: 'Apollo 12 left its lander’s bottom half and a science station called ALSEP on the Moon in November 1969.',
    orbitLine: 'Apollo 12, tell us about your precision landing!',
    chat: [
      'Apollo 12, you landed right beside Surveyor 3. Was that on purpose?',
      'Yes! We wanted to prove we could land exactly where we aimed.',
      'And you reached it on foot?',
      'The astronauts walked over and took parts home to study.',
      'What did you leave on the Moon?',
      'The bottom half of our lander, and a science station called ALSEP.',
      'What’s in it?',
      'A {{seismometer|quake sensor}}, a {{magnetometer|magnet sensor}}, and detectors for particles from the Sun.',
      'What did the crew bring home?',
      '34 kilograms of Moon rocks!',
      'Where are you now?',
      'In the {{ocean_storms|Ocean of Storms}}. We went quiet in 1977 along with the other science stations.',
      'A precise landing, Apollo 12!',
    ],
  }),
  mk({
    id: 'moon-apollo-14', name: 'Apollo 14', voice: 'apollo', emoji: '🚀', year: '1971',
    lead: 'We pulled a cart over the Moon!',
    body: 'Apollo 14 landed in the Fra Mauro highlands, set up a science station, and returned over 42 kg of samples.',
    speech: 'We landed in Fra Mauro and brought back 42 kilograms of Moon rock!',
    fact: 'Apollo 14 left its lander’s bottom half and an ALSEP science station on the Moon in 1971.',
    orbitLine: 'Apollo 14, what did you explore?',
    chat: [
      'Apollo 14, you went where Apollo 13 couldn’t go!',
      'Yes! After Apollo 13 had trouble, we got to visit {{fra_mauro|Fra Mauro}}.',
      'What’s there?',
      'Hilly ground covered with rocks thrown out by a giant crash long ago.',
      'How did the crew get around?',
      'On foot, pulling a little cart for tools. We didn’t have a rover.',
      'What did you leave on the Moon?',
      'The bottom half of our lander, and a science station.',
      'What did the station do?',
      'It had {{seismometer|quake sensors}} and a particle detector. It felt the Moon shake.',
      'What did you bring home?',
      'Over 42 kilograms of rocks and soil.',
      'And now?',
      'Quiet, since 1977.',
      'Thanks, Apollo 14.',
    ],
  }),
  mk({
    id: 'moon-lrv-16', name: 'Apollo 16 Rover', voice: 'apollo', emoji: '🚙', year: '1972',
    lead: 'Highlands road trip!',
    body: 'The Apollo 16 Lunar Roving Vehicle drove about 27 km across the Descartes highlands and was left behind.',
    speech: 'I carried Apollo 16 astronauts across the Descartes highlands!',
    fact: 'The Apollo 16 rover drove 26.7 km and was left on the Moon after the mission.',
    orbitLine: 'Apollo 16 Rover, tell us about your drive!',
    chat: [
      'Apollo 16 Rover, where did you take the astronauts?',
      'Across the {{descartes|Descartes Highlands}}. It was a bumpy ride!',
      'What were you made of?',
      'A light frame, four mesh wheels, and four electric motors. And two big batteries.',
      'Did you drive far?',
      'About 27 kilometers, in several trips.',
      'What did you carry?',
      'Two astronauts, their tools, and lots of Moon rocks.',
      'What did that help scientists learn?',
      'That highland rocks are different from the dark plains. We brought back almost 96 kilograms of samples!',
      'And now?',
      'Parked since April 1972, waiting.',
      'A great road trip!',
    ],
  }),
  mk({
    id: 'moon-apollo-16', name: 'Apollo 16', voice: 'apollo', emoji: '🚀', year: '1972',
    lead: 'We explored the highlands!',
    body: 'Apollo 16 landed in the Descartes Highlands, carried a rover and a science station, and brought home 95.7 kg of samples.',
    speech: 'We explored the lunar highlands and brought back 95 kilograms of samples!',
    fact: 'Apollo 16 left its lander’s bottom half, a rover, and an ALSEP science station on the Moon in April 1972.',
    orbitLine: 'Apollo 16, what did you find in the highlands?',
    chat: [
      'Apollo 16, you visited the Moon’s highlands.',
      'Yes! We landed in the {{descartes|Descartes Highlands}}, a very different place from the flat plains.',
      'What did you leave behind?',
      'The bottom half of our lander, a rover, and a science station.',
      'What did the station do?',
      'It had {{seismometer|quake sensors}}, a {{magnetometer|magnet sensor}}, and a heat probe.',
      'Did it all work?',
      'The heat probe got damaged while we were setting it up. But the rest worked well.',
      'What did the crew bring home?',
      'About 96 kilograms of rocks and soil.',
      'Where are you now?',
      'Still at Descartes. We went quiet in 1977.',
      'A great highland trip!',
    ],
  }),
  mk({
    id: 'moon-lrv-17', name: 'Apollo 17 Rover', voice: 'apollo', emoji: '🚙', year: '1972',
    lead: 'The longest Moon drive ever!',
    body: 'The Apollo 17 rover drove about 36 km across the Taurus-Littrow valley, the farthest of the three rovers.',
    speech: 'I drove about 36 kilometers on the Moon, farther than any other rover!',
    fact: 'The Apollo 17 rover drove 35.9 km, the longest of any Apollo rover, and stayed on the Moon.',
    orbitLine: 'Apollo 17 Rover, how far did you go?',
    chat: [
      'Apollo 17 Rover, you drove the farthest of all the Moon rovers!',
      'About 36 kilometers!',
      'Where did you drive?',
      'Around the {{taurus_littrow|Taurus-Littrow}} valley, with mountains on every side.',
      'What were you made of?',
      'A folding frame, four mesh wheels, and two big batteries.',
      'Did you find something special?',
      'Orange soil! The astronauts spotted it, and scientists were thrilled.',
      'What else did you carry?',
      'Tools, and 110 kilograms of rocks.',
      'Where are you now?',
      'Parked since December 1972.',
      'Thanks for the long drive.',
    ],
  }),
  mk({
    id: 'moon-apollo-17', name: 'Apollo 17', voice: 'apollo', emoji: '🚀', year: '1972',
    lead: 'The last people on the Moon, so far!',
    body: 'Apollo 17 was the final Apollo landing. It brought home the most samples, 110.5 kg, and left a rover and a science station.',
    speech: 'Apollo 17 was the final Moon landing so far, with the most samples ever!',
    fact: 'Apollo 17’s science station measured heat from inside the Moon, the pull of gravity, and the Moon’s thin gas.',
    orbitLine: 'Apollo 17, you were the last!',
    chat: [
      'Apollo 17, you were the last Apollo mission.',
      'We were. It was a very special trip.',
      'Who was on your crew?',
      'A geologist! Harrison Schmitt, the first scientist to walk on the Moon.',
      'What did you do?',
      'We drove the rover around {{taurus_littrow|Taurus-Littrow}} and collected rocks.',
      'What did you leave behind?',
      'The bottom half of our lander, a rover, and a science station.',
      'What did the station do?',
      'It had a heat probe, a gravity meter, and a sensor for the Moon’s thin {{exosphere|air}}.',
      'What did the crew bring home?',
      'More than any other mission: 110 kilograms.',
      'And now?',
      'We’re still on the Moon, quiet since 1977.',
      'The last footprints… for now.',
    ],
  }),
  mk({
    id: 'moon-alsep', name: 'ALSEP', voice: 'apollo', emoji: '🔋', year: '1969–72',
    lead: 'Moon science stations!',
    body: 'ALSEP stations were science kits set up on the Moon by Apollo crews, powered by nuclear batteries. They were switched off in 1977.',
    speech: 'Apollo crews set up science stations on the Moon, and they ran until 1977!',
    fact: 'The ALSEP stations were switched off on 30 September 1977. They are still on the Moon.',
    orbitLine: 'ALSEP, what did you do?',
    chat: [
      'ALSEP, what are you?',
      'A science kit! Apollo crews left five of us on the Moon.',
      'Which missions left one?',
      'Apollo 12, 14, 15, 16 and 17.',
      'What was inside?',
      '{{seismometer|Quake sensors}}, {{magnetometer|magnet sensors}}, heat probes, and particle detectors.',
      'What powered you? There’s no wall plug on the Moon.',
      'A {{rtg|nuclear battery}}. It turns heat into electricity.',
      'What did you learn?',
      'We felt moonquakes and space rocks hitting the Moon. And we measured heat flowing out of it.',
      'How long did you run?',
      'For years, until we were switched off on 30 September 1977.',
      'And now?',
      'Still on the Moon, at five sites.',
      'Silent now, but not forgotten.',
    ],
  }),
  mk({
    id: 'moon-lunar-prospector', name: 'Lunar Prospector', emoji: '🧲', year: '1998',
    lead: 'I looked for ice at the poles!',
    body: 'Lunar Prospector circled the Moon looking for ice and mapped what the Moon is made of. It ended with a planned crash in 1999.',
    speech: 'I circled the Moon looking for ice at the poles!',
    fact: 'Lunar Prospector found hints of water ice at the Moon’s poles. It was crashed near the south pole on 31 July 1999.',
    orbitLine: 'Lunar Prospector, did you find ice?',
    chat: [
      'Lunar Prospector, you went hunting for ice on the Moon!',
      'Yes, at the poles, where some spots never see sunlight.',
      'How did you hunt?',
      'With six instruments. Some sense rock chemistry, and one is a {{magnetometer|magnet sensor}}.',
      'And what did you find?',
      'Signs of hydrogen at both poles. That could mean water ice!',
      'Anything else?',
      'The Moon seems to have a small core, too.',
      'How did your mission end?',
      'I was crashed near the south pole on 31 July 1999.',
      'Why?',
      'Scientists hoped it would kick up water vapor to see.',
      'Did it work?',
      'No plume was seen. But my hints were enough to send more missions to look!',
      'You pointed the way, Lunar Prospector.',
    ],
  }),
  mk({
    id: 'moon-ladee', name: 'LADEE', emoji: '🌫️', year: '2013',
    lead: 'I tasted the Moon’s thin air!',
    body: 'LADEE circled the Moon to study its very thin atmosphere and dust. It ended with a planned crash in April 2014.',
    speech: 'I studied the thin air and dust around the Moon!',
    fact: 'LADEE hit the Moon on purpose on 18 April 2014.',
    orbitLine: 'LADEE, what did you taste up there?',
    chat: [
      'LADEE, the Moon has air?',
      'Barely! It’s called an {{exosphere|exosphere}}, so thin you can’t breathe it.',
      'What was your job?',
      'To find out what’s in that thin air, and what dust floats above the Moon.',
      'What tools did you carry?',
      'A dust detector, a gas sensor, and an ultraviolet camera.',
      'What did you learn?',
      'What gases drift around the Moon, and how dust rises and falls.',
      'How did your mission end?',
      'On 18 April 2014 I crashed into the Moon, on purpose.',
      'Where are you now?',
      'Near the edge of {{sundman|Sundman V crater}}.',
      'Thanks for tasting the Moon’s air!',
    ],
  }),
];

/* ------------------------------------------------------------------ */
/*  DEEP SPACE                                                         */
/* ------------------------------------------------------------------ */
export const DEEP_EXTRA = [
  mk({
    id: 'deep-mariner-5', name: 'Mariner 5', voice: 'mariner2', emoji: '🟡', year: '1967',
    lead: 'I woke up a year later!',
    body: 'Mariner 5 flew by Venus in 1967 and studied its air with radio waves. Contact ended in December 1967, but briefly returned in 1968.',
    speech: 'I flew by Venus in 1967, and I woke up again in 1968!',
    fact: 'Mariner 5 lost contact on 4 December 1967 and was briefly heard again on 14 October 1968.',
    orbitLine: 'Mariner 5, tell us about Venus!',
    chat: [
      'Mariner 5, you flew past Venus in 1967. What were you checking?',
      'Its {{atmosphere|air}}! I wanted to know how thick and how hot it is.',
      'How can a radio measure air?',
      'My radio signal passed through Venus’s air on the way to Earth. The air bent it a little, and that showed what the air is like.',
      'What did you find?',
      'It is very thick and very hot!',
      'What were you made of?',
      'Solar panels, a dish antenna, and a radio experiment.',
      'Did you keep talking to Earth?',
      'I went quiet in December 1967.',
      'But you came back, right?',
      'Yes! A year later, in October 1968, I woke up for a short while.',
      'Where are you now?',
      'Circling the Sun.',
      'A surprise comeback!',
    ],
  }),
  mk({
    id: 'deep-apollo-10-snoopy', name: 'Apollo 10 Snoopy', voice: 'apollo', emoji: '🐶', year: '1969',
    lead: 'Lost in orbit around the Sun!',
    body: 'Snoopy, Apollo 10’s lunar module, flew within 15 km of the Moon. Its top half was sent into orbit around the Sun in 1969 and never found.',
    speech: 'My top half was sent into orbit around the Sun in 1969, and nobody knows where I am!',
    fact: 'Snoopy’s top half was sent into orbit around the Sun in May 1969. No one has confirmed finding it.',
    orbitLine: 'Snoopy, where did you go?',
    chat: [
      'Snoopy, you’re named after a cartoon dog! What was your job?',
      'A dress rehearsal! Apollo 10 tested everything for the Moon landing, without landing.',
      'How close did you get?',
      'About 15 kilometers above the surface. So close!',
      'What did you test?',
      'My engine, my landing radar, and my steering. All worked.',
      'And what did you see?',
      'TV pictures of the surface, including where Apollo 11 would land.',
      'What are you built like?',
      'Two parts: a bottom half with legs, and a top half where the crew sits.',
      'What happened to you?',
      'The crew dropped my bottom half. My top half was sent into orbit around the Sun in 1969.',
      'Is it still there?',
      'Maybe! Nobody has confirmed finding me.',
      'Still out there, somewhere.',
    ],
  }),
  mk({
    id: 'deep-galileo', name: 'Galileo', voice: 'voyager', emoji: '🪐', year: '1989',
    lead: 'I orbited Jupiter for eight years!',
    body: 'Galileo circled Jupiter, studied its moons, and dropped a probe into its clouds. In 2003 it was sent into Jupiter on purpose.',
    speech: 'I circled Jupiter, dropped a probe into its clouds, and ended my mission in 2003!',
    fact: 'Galileo launched on 18 October 1989, sent its probe into Jupiter on 7 December 1995, and found hints of an ocean under Europa’s ice.',
    orbitLine: 'Galileo, what did you find at Jupiter?',
    chat: [
      'Galileo, you came with a little helper!',
      'A probe! It was attached to me until I got close to Jupiter, then I let it go.',
      'What did the probe do?',
      'It dived into Jupiter’s clouds and sent back data until it was crushed.',
      'And what did you do?',
      'I circled Jupiter for about eight years, studying the planet and its moons.',
      'What did you discover?',
      'Hints of a salty ocean under the ice of {{europa|Europa}}, and winds faster than a speeding train!',
      'Anything else?',
      'An asteroid with its own tiny moon!',
      'How did your mission end?',
      'In September 2003 I was steered into Jupiter on purpose.',
      'Why?',
      'To keep Earth germs from landing on a moon that might have life.',
      'Where are you now?',
      'Inside Jupiter. I don’t exist as a spacecraft anymore.',
      'Thanks for all you found, Galileo.',
    ],
  }),
  mk({
    id: 'deep-cassini', name: 'Cassini', voice: 'voyager', emoji: '💍', year: '1997',
    lead: 'I dove into Saturn!',
    body: 'Cassini circled Saturn for 13 years and carried the Huygens probe to Titan. It ended its mission in a planned dive into Saturn in 2017.',
    speech: 'I circled Saturn for thirteen years, then dove into the planet!',
    fact: 'Cassini launched on 15 October 1997 and carried the European Huygens probe to Saturn’s moon Titan.',
    orbitLine: 'Cassini, what did you see at Saturn?',
    chat: [
      'Cassini, you spent thirteen years at Saturn!',
      'Yes! I studied the planet, its rings, and its moons.',
      'What did you bring along?',
      'A small probe called Huygens. I dropped it onto {{titan|Titan}}, Saturn’s biggest moon.',
      'What was it like there?',
      'Orange haze and lakes! Huygens landed and sent pictures before going quiet.',
      'What else did you discover?',
      'Geysers of ice on {{enceladus|Enceladus}}, a tiny snowball of a moon.',
      'How were you powered?',
      'With a {{rtg|nuclear battery}}, since the Sun is far away at Saturn.',
      'How did your mission end?',
      'In September 2017 I dived into Saturn on purpose.',
      'Why?',
      'To keep Earth germs away from moons like Enceladus.',
      'Where are you now?',
      'In Saturn’s clouds. But Huygens is still on Titan!',
      'What a trip, Cassini.',
    ],
  }),
];